version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql_fornecedores
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fornecedores_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
